name: lxk0301-sync
on:
  schedule:
    - cron: '4 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-jiulan-DogDog
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync jiulan-DogDog
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/jiulan/platypus.git"
          source_branch: "main"
          destination_branch: "jiulan"
          github_token: ${{ secrets.PAT }}
